### ISSUE TITLE
Fail to show the avatar properly 

### ISSUE THREAD

**Issue by ghost** [jazzband/django-avatar#116]
The upload and change works, but the avatar can not show properly. There is just a broken image icon which means that the image can not display properly. 
<img width="102" alt="screen shot 2015-11-09 at 15 18 15" src="https://cloud.githubusercontent.com/assets/10586781/11027965/414aa246-86f5-11e5-891e-071f5c604ce0.png">

**Comment by zruu** [comment]
How have you setup in your templates? Can you give us any output? Have you loaded avatar_tags to your template?

**Comment by matam** [comment]
I have the same problem. Upload and change works but not display. When i tried receives avatars system generated error 404
----
Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/avatars/andrzej/resized/80/xyz.png
Using the URLconf defined in monitoring_server.urls, Django tried these URL patterns, in this order:
^admin/
^login/$
^logout/$
^start_page/$
^$
^avatars/ ^add/$ [name='avatar_add']
^avatars/ ^change/$ [name='avatar_change']
^avatars/ ^delete/$ [name='avatar_delete']
^avatars/ ^render_primary/(?P<user>[\w\d\@\.\-_]{3,30})/(?P<size>[\d]+)/$ [name='avatar_render_primary']
^avatars/ ^list/(?P<username>[\+\w\@\.]+)/$ [name='avatar_gallery']
^avatars/ ^list/(?P<username>[\+\w\@\.]+)/(?P<id>[\d]+)/$ [name='avatar']
The current URL, avatars/andrzej/resized/80/xyz.png, didn't match any of these.

**Comment by grantmcconnaughey** [comment]
@matam, that looks like a separate issue. Please open a new issue.

**Comment by grantmcconnaughey** [comment]
@rylanchiu, definitely going to need to see some source before I can determine what the issue is. Please post your template code here.

**Comment by johanneswilm** [comment]
Closing as likely solved. This could have to do with incorrect settings.
