### ISSUE TITLE
Django-avatar not show pictures

### ISSUE THREAD

**Issue by matam** [jazzband/django-avatar#117]
Upload and change using <a href="{% url 'avatar_change' %}">Change your avatar</a> works but this page don't display picture, also when i tried receives the proper avatars system generated error 404
## I'm using django-avatar 2.2.0

Page not found (404)
Request Method: GET
Request URL: http://127.0.0.1:8000/avatars/andrzej/resized/80/xyz.png
Using the URLconf defined in monitoring_server.urls, Django tried these URL patterns, in this order:
^admin/
^login/$
^logout/$
^start_page/$
^$
^avatars/ ^add/$ [name='avatar_add']
^avatars/ ^change/$ [name='avatar_change']
^avatars/ ^delete/$ [name='avatar_delete']
^avatars/ ^render_primary/(?P[\w\d\@.-_]{3,30})/(?P[\d]+)/$ [name='avatar_render_primary']
^avatars/ ^list/(?P[+\w\@.]+)/$ [name='avatar_gallery']
^avatars/ ^list/(?P[+\w\@.]+)/(?P[\d]+)/$ [name='avatar']
The current URL, avatars/andrzej/resized/80/xyz.png, didn't match any of these.
##  @grantmcconnaughey

![image](https://cloud.githubusercontent.com/assets/608413/11785089/32e58c4c-a280-11e5-8bb0-970cc68ebc3d.png)

**Comment by grantmcconnaughey** [comment]
Thanks! Please post your template code. Or are you using the default change.html?

**Comment by matam** [comment]
I'm using default change.html

**Comment by grantmcconnaughey** [comment]
This is odd. The URL should be pointing to your MEDIA_URL like this: `/media/avatars/username/resized/80/file.png`. Instead the URL is directly going to `/avatars/username/etc.`.

Which version of Django are you using?

**Comment by matam** [comment]
I'm using Django 1.8.6, Python 2.7.10 on Windows 7
IDE - PyCharm 5.0.1
Now I added  to settings.py this lines
MEDIA_ROOT = '/media/'
MEDIA_URL='127.0.0.1:8000/media/

And now when added avatars they are store in /media/avatars/<user> directory but system still generated page with error 404

Now link to the avatar look like: 
    <p>Your current avatar: </p>
    <img src="http://127.0.0.1:8000/media/avatars/andrzej/resized/80/34564807.png" alt="andrzej" width="80" height="80" />

![image](https://cloud.githubusercontent.com/assets/608413/11786809/eece054e-a288-11e5-8039-93250972166d.png)

**Comment by juanmieres** [comment]
add in urls.py fo your aplication
from "name_aplication" import settings
url(r'^media/(?P<path>.*)$',
     'django.views.static.serve',
     {'document_root':settings.MEDIA_ROOT}),

**Comment by Cheltigmashev** [comment]
I had the same problem. Try add static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) to your urlpatters. After this the application worked properly on django test server in my case. You can read more here: https://docs.djangoproject.com/en/dev/howto/static-files/#serving-other-directories
@juanmieres maybe your option is the same, I did not try this.

**Comment by c-shan** [comment]
the problem here. How did you solve it?

**Comment by johanneswilm** [comment]
This looks like a django issue. Please reopen if I misunderstood.
