### ISSUE TITLE
helper for use within django rest fw

### ISSUE THREAD

**Issue by patroqueeet** [jazzband/django-avatar#128]
dear #125 solves the issue like this:

```
def get_avatar(self, obj):
       """
       returns url for avatar
       """
      return avatar_url(obj.user)
```

but its not very pythonic to use a templatetag inside a serializer. any proper helper would be great!

**Comment by goodmind** [comment]
any updates?

**Comment by grantmcconnaughey** [comment]
@goodmind I'm not sure what you are asking. Pull requests are welcome.

**Comment by johanneswilm** [comment]
Closing as it is unclear what is being asked for. @goodmind @patroqueeet please provide PR.
