### ISSUE TITLE
Avatar/Change View does not work correctly. 

### ISSUE THREAD

**Issue by rnason** [jazzband/django-avatar#133]
Installed the app, plugged into my project, Gravatar is fetching correctly, but uploading a photo, doesn't work correctly. The file will upload, but the default avatar/change view doesn't show either the old Gravatar photo, or the new photo. I saw others having the same issue, tried following the steps that were in both other tickets to no avail. This should either run out of the box, with default settings, or there should be better documentation, especially for the routing and global settings.

**Comment by grantmcconnaughey** [comment]
Which version of Django are you using? Which version of Python?

**Comment by rnason** [comment]
Python 3.5, django 1.9

**Comment by grantmcconnaughey** [comment]
Hey @rnason, I'm finally getting around to looking into this. Is this what you see after uploading an image? The image simply doesn't load?

![image](https://cloud.githubusercontent.com/assets/4023140/18225795/f196322a-71c1-11e6-8840-c870d0a4e987.png)

**Comment by grantmcconnaughey** [comment]
Hmm, never mind. I just added `MEDIA_ROOT` and `MEDIA_URL` to my test project settings and now this works fine.

Here's a recording of it working for me: http://recordit.co/8IFNNXHnQe

**Comment by khizirsiddiqui** [comment]
I am working on Python 3.5, Django 1.10, and the same issue.
Here is what you said:
```
MEDIA_ROOT = '/media/'
MEDIA_URL = '/'
```
But this is still not working. I am still getting the same screen with no avatar. Even the {% avatar user %} does not render images except the default one.

**Comment by Cheltigmashev** [comment]
The same problem. Nothing helps.

**Comment by cmtruit** [comment]
This worked for me, in avatar/models.py

```
    def create_thumbnail(self, size, quality=None):
        # invalidate the cache of the thumbnail with the given size first
        invalidate_cache(self.user, size)
        try:
            orig = self.avatar.storage.open(self.avatar.name, 'rb')
            image = Image.open(orig)
            image = self.transpose_image(image)
            quality = quality or settings.AVATAR_THUMB_QUALITY
            w, h = image.size
            if w != size or h != size:
                if w > h:
                    diff = int((w - h) / 2)
                    image = image.crop((diff, 0, w - diff, h))
                else:
                    diff = int((h - w) / 2)
                    image = image.crop((0, diff, w, h - diff))
                if image.mode in ('RGBA', 'LA'):
                   mode = image.mode
                   alpha = image.getchannel('A')
                   image = image.convert(mode[:-1]) \
                       .convert('P', palette=Image.ADAPTIVE, colors=255)
                   mask = Image.eval(alpha, lambda px: 255 if px < 128 else 0)
                   image.paste(255, mask)
                   image.info['transparency'] = 255
                if image.mode not in ("RGB", "RGBA"):
                    image = image.convert("RGB")
                image = image.resize((size, size), settings.AVATAR_RESIZE_METHOD)
                thumb = six.BytesIO()
                image.save(thumb, settings.AVATAR_THUMB_FORMAT, quality=quality)
                thumb_file = ContentFile(thumb.getvalue())
            else:
                thumb_file = File(orig)
            thumb = self.avatar.storage.save(self.avatar_name(size), thumb_file)
        except IOError as error:
            print("ERROR: ", error )
```

**Comment by Pzhuang** [comment]
I think the problem is because the avatar is save to media\avatars\test
And media\avatars\test\resized\80 is the route we reference to. So we need to change it I guess.
But can someone tell me how to do that?

**Comment by johanneswilm** [comment]
This has likely been solved with recent releases. Please reopen if it has not.
