### ISSUE TITLE
Generated Avatars

### ISSUE THREAD

**Issue by Cheltigmashev** [jazzband/django-avatar#148]
How can I make generation of users' avatars instead using sinlge default avatar? I read docs but did not understand how to do this.

**Comment by bbb1991** [comment]
If you want generate default avatars with Gravatar, follow steps below:
0. Install `django-avatar`, follow steps 1, 2 and 3 on official django-avatar documentation. 
1. Insert `AVATAR_GRAVATAR_DEFAULT` variable in `settings.py` file and set value (identicon, monsterid, wavatar or retro).  For example:
```python
AVATAR_GRAVATAR_DEFAULT='retro'
```
You can read more about values on [Gravatar documentation](https://en.gravatar.com/site/implement/images/#default-image)

2. In your html file, load template tags:
```
{% load avatar_tags %}
```
3. Show generated avatar on html. For example for current user:
```
{% avatar request.user %}
```
4. ???
5. Profit!

In my opinion, you should use your own generator, or other open source. I'd suggest [Dicebear](https://avatars.dicebear.com/).
