### ISSUE TITLE
Upload Issue - No Resized Images Generated

### ISSUE THREAD

**Issue by digitalhurricane-io** [jazzband/django-avatar#153]
When I upload a new avatar via http://127.0.0.1:8000/avatar/change/ it uploads successfully, however the resized images are not created and so the avatar images are not displayed.

The avatar image is uploaded to /media/avatars/paul/flame_350_vknNF9f.png

It's linking to /media/avatars/paul/resized/80/flame_350_vknNF9f.png and so returns a 404

The 'resized' and '80' directories do not exist.

I don't get any kind of traceback. This is what I get in the terminal:
Not Found: /media/avatars/paul/resized/80/flame_350_bGtZsFN.png
[01/Aug/2017 05:32:54] "GET /media/avatars/paul/resized/80/flame_350_bGtZsFN.png HTTP/1.1" 404 1880

I'm using python 3.5.3, Django 1.11.3, django-avatar 4.0.0, Pillow 4.2.1, ubuntu 17.04

**Comment by digitalhurricane-io** [comment]
Looks like I'm getting an IOerror in the create_thumbnail() function in models.py

I had to add a print statement to be sure. It doesn't alert the user in any way when it happens. just returns.
except IOError:
            print('IOError')
            return  # What should we do here?  Render a "sorry, didn't work" img?

I'll update after more testing.

**Comment by digitalhurricane-io** [comment]
OK. Figured it out.
Things have changed a bit in recent versions of Pillow.

Therefore, if you try to upload a png and AVATAR_THUMB_FORMAT is set to 'JPEG', the image upload will fail silently with an IOError:  cannot write mode RGBA as JPEG

If the AVATAR_THUMB_FORMAT is set to 'PNG' everythings fine.

Here is a link to the Pillow issue that helped me out with this. https://github.com/python-pillow/Pillow/issues/2609

The alpha channel must first be removed to save the png as jpeg like so:
image = image.convert("RGB")

The the create_thumbnail() function in models.py will need to be edited to fix this

**Comment by hnphan** [comment]
I ran into the same issue. Made a pull request above.
@digitalhurricane-io a work around would be to use an older version of Pillow. I tried using '4.1.1' and it worked.

**Comment by lggwettmann** [comment]
I'm running django-avatar 4.1.0

**Comment by Lone1567** [comment]
Any update on this? Are we forced to make users choose one type of image format out of the box? Experiencing the same issue with 4.1.0

**Comment by grantmcconnaughey** [comment]
@Lone1567 I think we're just waiting for a PR on this one.

**Comment by grking8** [comment]
submitted PR https://github.com/grantmcconnaughey/django-avatar/pull/179

**Comment by ntoll** [comment]
I  just encountered this problem too.

**Comment by sergioisidoro** [comment]
Also encountered this issue. This project seems to be quite low on maintenance, with last merge being on 2020.
I wonder if it would be a candidate for https://github.com/jazzband , since other great Django projects are also harboured there.
