### ISSUE TITLE
change height width attribute value

### ISSUE THREAD

**Issue by anuj9196** [jazzband/django-avatar#158]
I'm using latest version of this plugin, it's an awesome plugin.

I want to display user avatar which if of 400x400 but img attribute's `height` and `width` property set to `100%` or something other than `400` or get `width` and `height` attribute removed, like
```
<img src="image_path_of_400x400" class="img-responsive" alt="name" width="100%" height="100%">

OR 

<img src="image_path_of_400x400" class="img-responsive">
```

I tried
```
{% avatar user 400 class="img-responsive" width="100%" height="100%" %}
```

But it always prints
```
<img src="image_path_of_400x400" class="img-responsive" alt="name" width="400" height="400">
```

**Comment by TheSecEng** [comment]
You shouldn't use width and height in this manner. If you are going to use avatar images and need to set height and width. I suggest you utilize a CSS and the class name.

Also, this is acting as intended.

You are specifying user 400 which tells it to set the width and height to 400. 

```{% avatar user 400 class="img-responsive" width="100%" height="100%" %}```

I suggest you use something like this.

HTML file
```{% avatar user class="img-responsive avatar" %}```

CSS
```.Img-responsive.avatar { height: 100%; width: 100%;}```

**Comment by BadGrem** [comment]
I did as you said , but it was doesn't work.
Because the <img> has the attribute value "width" and "height" , we can't use css to cover it.

`<img src="https://www.gravatar.com/avatar/c4ca4238a0b923820dcc509a6f75849b/?s=80" width="80" height="80" class="rounded img-responsive avatar" alt="954">`

**Comment by BadGrem** [comment]
Oh, I'm so sorry.
I find the problem , I forgot to clear the broswer cache , So you are right !

**Comment by aklson-datascientist** [comment]
If I set the image's width and height properties to be larger that than the default which is 80px, a blurry version of the image is rendered.

**Comment by johanneswilm** [comment]
This is working as intended.
