### ISSUE TITLE
AttributeError at /avatar/delete/: 'NoneType' object has no attribute 'send'

### ISSUE THREAD

**Issue by artemrizhov** [jazzband/django-avatar#16]
Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/avatar/delete/
Django Version: 1.1
Python Version: 2.6.5
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.webdesign',
 'multilingual',
 'multilingual.flatpages',
 'news',
 'news.templatetags',
 'feedback',
 'article',
 'article.templatetags',
 'institution',
 'institution.templatetags',
 'baner',
 'baner.templatetags',
 'threadedcomments',
 'django.contrib.comments',
 'rosetta',
 'captcha',
 'tools',
 'tools.templatetags',
 'accounts',
 'avatar',
 'debug_toolbar']
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'multilingual.middleware.DefaultLanguageMiddleware',
 'multilingual.flatpages.middleware.FlatpageFallbackMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware')

Traceback:
File "/home/artem/prog/dev/anastasia_u4eba/env/lib/python2.6/site-packages/django/core/handlers/base.py" in get_response
1.                 response = callback(request, _callback_args, *_callback_kwargs)
   File "/home/artem/prog/dev/anastasia_u4eba/env/lib/python2.6/site-packages/django/contrib/auth/decorators.py" in **call**
2.             return self.view_func(request, _args, *_kwargs)
   File "/home/artem/prog/dev/anastasia_u4eba/env/lib/python2.6/site-packages/avatar/views.py" in delete
3.                         notification.send([request.user], "avatar_updated", {"user": request.user, "avatar": a})

Exception Type: AttributeError at /avatar/delete/
Exception Value: 'NoneType' object has no attribute 'send'

**Comment by johanneswilm** [comment]
This code is no longer present in django-avatar.
