### ISSUE TITLE
Broken link to default avatar url

### ISSUE THREAD

**Issue by dismine** [jazzband/django-avatar#166]
Hi,

I use version `4.1.0` and experience broken link to default avatar url. When my user did not specified an avatar and gravatar also cannot provide appropriate for the user, by default it should fall back to default avatar. Option **AVATAR_DEFAULT_URL** specify which image to take. I use value by default: `avatar/img/default.jpg`. The problem is a browser cannot find the image. I know that Django-Avatar shipped with such, but for some reasons it saved in `media` folder. Can someone tell me is it intended? According to Django documentation to serve static files they must be in folder defined by STATIC_URL variable.

I resolved this issue by copying default path folder to my static folder, now Django can map it.

**Comment by morenoh149** [comment]
same here on 5.0. The template produces an <img> tag to `/static/avatar/img/default.jpg`.

We see a default avatar in the source code at https://github.com/grantmcconnaughey/django-avatar/blob/master/avatar/media/avatar/img/default.jpg Should this image be copied over during installation of the package?
