### ISSUE TITLE
Not all cached avatars are deleted by invalidate cache

### ISSUE THREAD

**Issue by rafiqhilali** [jazzband/django-avatar#172]
function `avatar.utils.invalidate_cache` only deletes these sizes
```python
sizes = set(settings.AVATAR_AUTO_GENERATE_SIZES)
```

this means that any sizes that have been generated on the fly will not be removed from cache, and then will display even after that avatar has been deleted.

I've made a fix for this by adding to the cache a key `<user>__cached_sizes`. Whenever a size is cached it is added to this set. The invalidate cache function then just deletes the sizes in this set.

**Comment by rafiqhilali** [comment]
fixed by #173

**Comment by johanneswilm** [comment]
Fixed in 7.0.0.
