### ISSUE TITLE
Avatar deletion doesn't fails if image is not found in storage

### ISSUE THREAD

**Issue by rafiqhilali** [jazzband/django-avatar#176]
When using storage backends that raise exceptions when `storage.delete()` is called if the file is not present in the storage (Not the default `FileSystemStorage` but a few custom storages for cloud buckets will) .

Then the `remove_avatar_images` method that is triggered by the `post_delete` signal fails and stops the deletion of the `Avatar` instance. This can occur if there was an issue with the upload.

Fix is to check for the presence of the image before calling `.delete()`

I've raise a PR here - #177

**Comment by johanneswilm** [comment]
Merged in 6.0.0
