### ISSUE TITLE
Thumbnails Not created due to outdated Pillow

### ISSUE THREAD

**Issue by cjshaw1976** [jazzband/django-avatar#178]
Good Day, 

First of all, I really like this package. Good job.

I had found that the sized avatars are not being created. Diving deeper into the issue, the error being ignored was:

> OSError: cannot write mode RGBA as JPEG

From https://github.com/python-pillow/Pillow/issues/2609, I found the simple solution was to uninstall **Pillow==5.4.1** and install **Pillow==4.1.1**.

Please may the package be updated to support new versions of Pillow.

Thank you.

**Comment by johanneswilm** [comment]
I also found this. Unfortunately this only shows if one lifts the thumbnail creation out of this try-except block: https://github.com/grantmcconnaughey/django-avatar/blob/master/avatar/models.py#L163-L185.

The solution seems to be to put this into the settings.py:
```
AVATAR_THUMB_FORMAT = "PNG"
```

**Comment by lggwettmann** [comment]
Is there an update for this? Would it be possible to update the Pillow dependency? Thanks in advance.

**Comment by morenoh149** [comment]
@lggwettmann it sounds like users are installing a later version of pillow (v5) which needs to use the png format. So there is only a problem if you want to use a modern pillow and NOT use png. What is your issue?

**Comment by johanneswilm** [comment]
Solved in https://github.com/jazzband/django-avatar/commit/2fb30345058df5976c044f4e72fe4d671b399b38 which makes the modes configurable.
