### ISSUE TITLE
data protection issues

### ISSUE THREAD

**Issue by joriki** [jazzband/django-avatar#181]
We're trying to make our site GDPR-compliant, and I came across two privacy issues with this app.

The first is simply that avatar image files aren't deleted when a user is deleted. Of course one could first delete the avatars (though see #175), but one would sort of expect everything related to a user to be deleted together with the user (as is the case with database entries).

The second issue is a bit more subtle. The setting `AVATAR_EXPOSE_USERNAMES` is `True` by default, which causes the usernames to be exposed as directory names in the avatar image storage. I don't see the upside to this; it would seem preferable to me to make this `False` by default (in which case the directories are named by user IDs). But more problematic than the use of current usernames is the fact that when a user's username is changed, the directory isn't moved but continues to be named by the old username. For the original uploaded images, this isn't a problem, since their filenames are stored in the `Avatar` model, so they can still be retrieved and deleted. But the cached resized images in the `resized` directories are orphaned by this change -- nothing points to them anymore, they're still in the old username directory but can't be accessed or deleted; when they're needed, they get regenerated under the new username. Thus, even if all the user's avatars are deleted before the user is deleted, a directory will still hang around that's named by a previous username and contains cached resized avatar images of the user.

I wrote [a migration](https://github.com/DemokratieInBewegung/plenum/blob/97_anonymize_users/voty/initproc/migrations/0037_anonymize_avatars.py) that resolves this situation by collecting all accessible avatar images in directories named by user IDs and deleting the remaining cached images.

**Comment by mina-gaid** [comment]
Hi @joriki 

In regards to avatar image files not deleting when a user is deleted: default behavior in Django is to not delete an associated file when a model instance is deleted.
It's good standard for packages like this to behave in the default manner.

If, for a particular project, it's preferable to delete files when a model instance is deleted, let me introduce you one of my favorite Django packages - [django-cleanup.](https://github.com/un1t/django-cleanup)

It's exactly what you need.

It takes less than a minute to set up and works beautifully with images or all media files in general.

No code needed, just `pip install django-cleanup` and add it to your `INSTALLED_APPS` settings (making sure to always place last, under all the other apps).

I am not a maintainer of django-avatar so I can't really help you with your other issue. 
Hope someone else can look into it and provide a solution.

**Comment by johanneswilm** [comment]
Hey,
I am currently looking at merging different things here and being GDPR compliant is important for a lot of projects right now. However, the comment by @mina-gaid makes me think that #175 should not be merged and there is a valid alternative. Do you agree with that @joriki ? If so, can we close this issue or do we need to do something more about this?

**Comment by johanneswilm** [comment]
As of Django 7.0.0, `AVATAR_CLEANUP_DELETED` is on by default. The other issues have also been delt with in 6.0.0 and 7.0.0.
