### ISSUE TITLE
Please tag releases in git

### ISSUE THREAD

**Issue by stevecj** [jazzband/django-avatar#186]
Since python distribution packages do not include license files and we need to bundle licenses of 3rd party software that we use in our project, we use a script to retrieve licenses from source repositories.

In order to make sure we have the right license file for the current version, we generate version-specific URLs that assume there is a tag for the version.

This stopped working with django-avatar because there are no longer tags for recent versions.

**Comment by jezdez** [comment]
@johanneswilm Can you go through the commits and add the git tags please?

**Comment by johanneswilm** [comment]
I was going to make a tag for the upcoming 6.0.0 release. But we also need
this for earlier releases?

**Comment by jezdez** [comment]
@johanneswilm Yeah, it's good practice to be able to point to past releases, not sure why it wasn't done before.

**Comment by johanneswilm** [comment]
Done.
