### ISSUE TITLE
 redirect does not work

### ISSUE THREAD

**Issue by ogurec-ogurec** [jazzband/django-avatar#195]
Hello, i installed the application, launched it, set the tags, run: add avatar, upload, click add. The avatar is loading, but nothing happens on the page utomatically we remain on the same page without visual changes. (The page does not refresh)
I suspect that this part does not work:

_\Lib\site-packages\avatar\views.py: 117_

`return redirect (next_override or _get_next (request))`

If you manually go "back", the message "About successful download" will be displayed.
What to do?

**Comment by ogurec-ogurec** [comment]
How can I define page (example profile.html) to redirect after the operation?

**Comment by ogurec-ogurec** [comment]
It seems to have figured it out. If someone needs: you need to replace this line: 
`return redirect (next_override or _get_next (request))`

**Comment by johanneswilm** [comment]
@ogurec-ogurec Is this a bug? What did you replace that line with?

**Comment by johanneswilm** [comment]
Closing this issue as no further feedback was received and it's unclear if this is still an issue. @ogurec-ogurec please reopen if this continues to be an issue.
