### ISSUE TITLE
Fix RemovedInDjango40Warning warnings to support Django 4.0

### ISSUE THREAD

**Issue by alexbieg-skilljar** [jazzband/django-avatar#202]
Django 4.0 was release recently and we have begun seeing `RemovedInDjango40Warning` warnings in our console. There may be more, but these are the warnings we are seeing:

* `RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().`
* ` RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().`
* `RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.`

**Comment by darkpixel** [comment]
This is now a blocker.  Django 4.x has been released and django-avatar is not compatible.

django-gravatar is compatable and is pretty much a drop-in replacement: https://github.com/twaddington/django-gravatar

**Comment by pnizet** [comment]
@grantmcconnaughey do you plan to update [django-avatar](https://github.com/grantmcconnaughey/django-avatar) to be compatible to django 4.0 ? i saw that you've merge branches that seems to correct the problems...
Thanks

**Comment by johanneswilm** [comment]
Fixed in version 6.0.0.
