### ISSUE TITLE
Resized avatar getting double rotation in Safari

### ISSUE THREAD

**Issue by siovene** [jazzband/django-avatar#207]
Images with an EXIF rotation get rotated two times when using Safari.

 - The first time the rotation is hardcoded because of `transpose_image` in `models.py`
 - Then Safari sees that the resulting thumbnail still has an EXIF rotation header, and rotates it again

Since the generated thumbnail is transposed, shouldn't the EXIF rotation header be dropped in the thumbnail?

Thanks!

**Comment by siovene** [comment]
Please see this:

https://github.com/python-pillow/Pillow/issues/4537

**Comment by siovene** [comment]
Replacing `transpose_image` with the following code fixes the issue for me:

```
        def transpose_image(self, image):
            EXIF_ORIENTATION = 0x0112
            code = image.getexif().get(EXIF_ORIENTATION, 1)
            if code and code != 1:
                image = ImageOps.exif_transpose(image)

            return image
```

**Comment by johanneswilm** [comment]
@siovene It's a bit unclear - does this only happen for older versions of Pillow or also newer ones? I don't have a mac, so I cannot easily test this. But if someone contributes a PR and others can verify that it is working, I work on merging it.

**Comment by siovene** [comment]
Thanks for fixing!
