### ISSUE TITLE
BUG  Custom User Model in Django E039

### ISSUE THREAD

**Issue by teury** [jazzband/django-avatar#238]
This happens when you have a custom user model in django

```
<class 'avatar.admin.AvatarAdmin'>: (admin.E039) An admin for model 
"User" has to be registered to be referenced by AvatarAdmin.autocomplete_fields.
```

https://github.com/jazzband/django-avatar/blob/8fa396f5b05528f9cfc7337e8b5c641e03168e8e/avatar/admin.py#L13

Apparently it was caused by this commit. https://github.com/jazzband/django-avatar/pull/219

**Comment by johanneswilm** [comment]
Hey @teury,
it should be possible to use a custom user model here - I have done that. But you need to register the user model in the admin somewhere. Else it doesn't know how to show the admin screen.
