### ISSUE TITLE
Add field has_custom_avatar to user profile or similar table.

### ISSUE THREAD

**Issue by evgenyfadeev** [jazzband/django-avatar#25]
Hello, we fixed this issue in askbot - each user has a denormalized record on whether they have a real avatar or not.
Actually - the record stores type of avatar: auto-gravatar, uploaded gravatar, locally uploaded avatar.

Would you like to include this into django-avatar? Probably most of the code can be borrowed from askbot, we could help too.

This record helps to avoid displaying auto-generated gravatars, which look quite ugly especially if you show a few side by side.

**Comment by johanneswilm** [comment]
@evgenyfadeev Sure - just make a PR.
