### ISSUE TITLE
Gravatar Link Typo (?)

### ISSUE THREAD

**Issue by alanthony** [jazzband/django-avatar#4]
Hello,

(Please let me know if I need to follow a different protocol for submitting this piece of information.  It's my first time submitting anything to an open source project.)

```
    if AVATAR_GRAVATAR_BACKUP:
        # didn't work:
        #return "http://www.gravatar.com/avatar/%s/?%s" % (

        # works (note the slash before the ? is removed):
        return "http://www.gravatar.com/avatar/%s?%s" % (
            hashlib.md5(user.email).hexdigest(),
            urllib.urlencode({'s': str(size)}),)
            )
```

When defaulting to a Gravatar, my application was not finding the actual Gravatar but was instead always returning the default blue Gravatar "G".  I compared the link text in the code with the link format spec on Gravatar.com and found that there was an extra slash at the end of the link.  I removed this on my install, and now it works.

Thanks.

**Comment by johanneswilm** [comment]
Checked and the url works fine in 2022.
