### ISSUE TITLE
Problem when deleting user with avatar

### ISSUE THREAD

**Issue by jwierzbo** [jazzband/django-avatar#52]
When I'm trying delete user (who has some avatars) from admin panel, I get an error:

DoesNotExist at /admin/auth/user/
User matching query does not exist. Lookup parameters were {u'id__exact': 11}
Exception Location: /usr/local/lib/python2.7/dist-packages/django/db/models/query.py in get, line 389

/home/testDjango/frontend/avatar/models.py in invalidate_avatar_cache
    invalidate_cache(instance.user) ...
▼Local vars
Variable    Value
instance  
<Avatar: Avatar for test>
sender  
<class 'avatar.models.Avatar'>
kwargs  
{'signal': <django.dispatch.dispatcher.Signal object at 0x250c050>,
 'using': 'default'}

**Comment by joriki** [comment]
The pull request is #65, and it hasn't been merged yet. (Just saying; I don't know if the problem persists.)
