### ISSUE TITLE
Resize problem

### ISSUE THREAD

**Issue by cahitonur** [jazzband/django-avatar#53]
Hello,
Uploading avatars works good but it doesn't create a resized folder nor resized images.
Any idea?

**Comment by brunobastosg** [comment]
I was having the same problem and followed @sergeny steps, but it didn't work. The path to the libraries are different in my computer and PIL failed to install. Here is what I had to do:

    sudo pip uninstall PIL

    sudo apt-get install libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev

    sudo ln -s /usr/lib/i386-linux-gnu/libjpeg.so /usr/lib
    sudo ln -s /usr/lib/i386-linux-gnu/libfreetype.so /usr/lib
    sudo ln -s /usr/lib/i386-linux-gnu/libz.so /usr/lib

    sudo pip install -U PIL --allow-external PIL --allow-unverified PIL
