### ISSUE TITLE
render_primary() view behaves differently than "avatar" template tag.

### ISSUE THREAD

**Issue by danostrowski** [jazzband/django-avatar#8]
If you use the avatar template tag, django-avatar will fall back to gravatar if it's configured. However, when the view render_primary() is used, there is no gravatar fallback.

I didn't really find this clearly documented anywhere and I found the behavior inconsistent.

**Comment by johanneswilm** [comment]
`AVATAR_GRAVATAR_BACKUP` setting has been removed in https://github.com/jazzband/django-avatar/pull/137 .
