### ISSUE TITLE
Support non standard settings

### ISSUE THREAD

**Issue by moimael** [jazzband/django-avatar#93]
Hi,

I wanted to use django-avatar but my app isn't organize like a basic django app, and my env dependent settings are loaded in a .env file.

├── proj_name
│   ├── .env
│   ├── settings.py
│   ├── url.py
├── apps
│   ├── some_app
│   ├── some_app
│   ├── core
│   └── some_app
├── etc
├── libs
├── project
│   ├── deploy
│   └── doc
└── var
└── README.rst

So when I try to use django-avatar i get this : 

```
AttributeError: 'Settings' object has no attribute 'AVATAR_DEFAULT_SIZE'
```

Any thought on how to fix this ?

Thanks !

**Comment by johanneswilm** [comment]
The settings file has been removed a while ago.
